### ISSUE TITLE
Incorrect pvalue analysis for "Endangerment of species"

### ISSUE THREAD

**Issue by JagaRamesh** [sornon1/intro-data-capstone-biodiversity#1]
The pvalue should not be expressed in %. 
The pvalue is the probability that "the difference between species is by chance". 

pvalue for Mammals/Birds contingency test is 0.68.
Since the pvalue is not less than 0.05, we conclude that the difference between Mammals and birds are not significant. So, we conclude both Mammals and Birds as highly endangered species.

Pvalue for Mammals/Reptile test is 0.03.
Since the pvalue is less than 0.05, we conclude that the difference between Mammals and Reptile is significant. So, we conclude that Mammals are more endangered than Reptile.

**Comment by sornon1** [comment]
Ah understood. I think of them in terms of percentages, but def get that is not the right way to notate it!

**Comment by sornon1** [comment]
@JagaRamesh I've updated the presentation now. My calculations in the notebook were correct, right?

**Comment by JagaRamesh** [comment]
Yes. the calculations are correct.
